# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.1' # The Go version to download (if necessary) and use.

      - name: login docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/leuchtdiode
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build & deploy
        run: |
          go version

          DOCKER_IMAGE=ghcr.io/luechtdiode/storj-velero-plugin
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | sed "s!/!-!g")
          DOCKER_TAG=${BRANCH_NAME}

          echo $DOCKER_IMAGE, $BRANCH_NAME, $DOCKER_TAG

          make plugin-build

          docker push $DOCKER_IMAGE:$DOCKER_TAG
